#ifndef _MAPSCREEN_QUOTES__H_
#define _MAPSCREEN_QUOTES__H_


//Enums for the quotes Jerry Milo can say
enum
{
	MILO_QUOTE__OPENING_GREETING_PART_1,
	MILO_QUOTE__OPENING_GREETING_PART_2,
	MILO_QUOTE__FRIENDLY_APPROACH_NOTHING_TO_SAY,
	MILO_QUOTE__FRIENDLY_APPROACH_NOTHING_TO_SAY_ALT,
	MILO_QUOTE__REFUSE_TO_ACCEPT_ITEM,
	MILO_QUOTE__DIRECT_APPROACH_NOTHING_TO_SAY,								//5
	MILO_QUOTE__THREATEN_APPROACH_NOTHING_TO_SAY,
	MILO_QUOTE__RECRUITMENT_REFUSAL,
	MILO_QUOTE__WOUNDED,
	MILO_QUOTE__GET_LOST,
	MILO_QUOTE__ACCEPT_MONEY,																	//10
	MILO_QUOTE__PLAYER_HAS_MORE_THEN_6_MERCS,
	MILO_QUOTE__PLAYER_HAS_MORE_THEN_6_MERCS_2ND_TIME,
	MILO_QUOTE__PLAYER_HAS_LESS_THEN_6_MERCS,
	MILO_QUOTE__CRASH_QUOTE,
	MILO_QUOTE__FOLLOWS_PC_ANSWER_TO_14_PART_1,								//15
	MILO_QUOTE__FOLLOWS_PC_ANSWER_TO_14_PART_2,
	MILO_QUOTE__FOLLOWS_PC_ANSWER_TO_14_PART_3,
	MILO_QUOTE__ALTERNATE_DIRECT_DEFAULT,
	MILO_QUOTE__FIRST_RESPONSE_TO_THREATENING,
	MILO_QUOTE__DEFAULT_COWERING_QUOTE,												//20
	MILO_QUOTE__HEADED_TO_TRACONA_QUOTE,
	MILO_QUOTE__JERRY_HEALED,
	MILO_QUOTE__JERRY_BECOMES_ENEMY,
	MILO_QUOTE__ALREADY_HAS_6_MERCS,
	MILO_QUOTE__PLAYER_HAS_NO_MERCS,


	MILO_NO_QUOTE = 0xFFFF,
};




void JerryMiloTalk( UINT16 usQuoteNum );

BOOLEAN HasJerryMiloSaidQuoteBefore( UINT32 uiQuoteID );

void JerryMiloSaidQuote( UINT32 uiQuoteID );

BOOLEAN WillJerryMiloAllowThePlayerToCompressTimeAtBeginingOfGame();

void HaveJerrySayWhyPlayerCantTimeCompressAtBeginningOfGame();

BOOLEAN DoesPlayerHaveNoMercsHiredAndJerryHasntSaidQuoteYet();

void HandleJerryMiloQuotes( BOOLEAN fReset );

void JerryMiloDelayedTalk( UINT16 usQuoteNum, UINT32 uiDelay );

void InitJerryQuotes();

BOOLEAN DidPlayerInitiallyHaveLessThen6MercsAndNowHaveExactly6AndHasntSaidFullLoadQuote();

#endif
