#ifndef __IMP_CHARACTER_TRAIT__H_
#define __IMP_CHARACTER_TRAIT__H_

#include "Types.h"

void EnterIMPCharacterTrait( void );
void RenderIMPCharacterTrait( void );
void ExitIMPCharacterTrait( void );
void HandleIMPCharacterTrait( void );

//enum
//{
typedef enum
{
	IMP_ATTITUDE_NORMAL = 0,
	IMP_ATTITUDE_FRIENDLY,
	IMP_ATTITUDE_LONER,
	IMP_ATTITUDE_OPTIMIST,
	IMP_ATTITUDE_PESSIMIST,
	IMP_ATTITUDE_AGGRESSIVE,
	IMP_ATTITUDE_ARROGANT,
	IMP_ATTITUDE_BIGSHOT,
	IMP_ATTITUDE_ASSHOLE,
	IMP_ATTITUDE_COWARD,
	IMP_NUMBER_ATTITUDES,
};

typedef enum
{
	IMP_CHARACTER_TRAIT_NORMAL = 0,
	IMP_CHARACTER_TRAIT_SOCIABLE,
	IMP_CHARACTER_TRAIT_LONER,
	IMP_CHARACTER_TRAIT_OPTIMIST,
	IMP_CHARACTER_TRAIT_ASSERTIVE,
	IMP_CHARACTER_TRAIT_INTELLECTUAL,
	IMP_CHARACTER_TRAIT_PRIMITIVE,
	IMP_CHARACTER_TRAIT_AGGRESSIVE,
	IMP_CHARACTER_TRAIT_PHLEGMATIC,
	IMP_CHARACTER_TRAIT_DAUNTLESS,
	IMP_CHARACTER_TRAIT_PACIFIST,
	IMP_CHARACTER_TRAIT_MALICIOUS,
	IMP_CHARACTER_TRAIT_SHOWOFF,
	IMP_NUMBER_CHARACTER_TRAITS,
};

INT8 iChosenCharacterTrait();

STR16 gzIMPCharacterTraitText[];
STR16 gzIMPAttitudesText[];

#endif
