#ifndef ACTION_ITEMS_H

#define ACTION_ITEMS_H

typedef enum
{
	ACTION_ITEM_OPEN_DOOR = 1,
	ACTION_ITEM_CLOSE_DOOR,
	ACTION_ITEM_BLOW_UP,
	ACTION_ITEM_SMALL_PIT,
	ACTION_ITEM_LARGE_PIT,
	ACTION_ITEM_TOGGLE_DOOR,
	ACTION_ITEM_TOGGLE_ACTION1,
	ACTION_ITEM_TOGGLE_ACTION2,
	ACTION_ITEM_TOGGLE_ACTION3,
	ACTION_ITEM_TOGGLE_ACTION4,
	ACTION_ITEM_ENTER_BROTHEL,
	ACTION_ITEM_EXIT_BROTHEL,
	ACTION_ITEM_KINGPIN_ALARM,
	ACTION_ITEM_SEX,
	ACTION_ITEM_REVEAL_ROOM,
	ACTION_ITEM_LOCAL_ALARM,
	ACTION_ITEM_GLOBAL_ALARM,
	ACTION_ITEM_KLAXON,
	ACTION_ITEM_UNLOCK_DOOR,
	ACTION_ITEM_TOGGLE_LOCK,
	ACTION_ITEM_UNTRAP_DOOR,
	ACTION_ITEM_TOGGLE_PRESSURE_ITEMS,
	ACTION_ITEM_MUSEUM_ALARM,
	ACTION_ITEM_BLOODCAT_ALARM,
#ifdef JA2UB
	ACTION_ITEM_BIGGENS_BOMBS,
	ACTION_ITEM_BIGGENS_WARNING,
	ACTION_ITEM_SEE_FORTIFIED_DOOR,
	ACTION_ITEM_OPEN_FORTIFED_DOOR,
	ACTION_ITEM_SEE_POWER_GEN_FAN,
	ACTION_ITEM_NEW = ACTION_ITEM_SEE_POWER_GEN_FAN + 215
#else
	ACTION_ITEM_NEW = ACTION_ITEM_BLOODCAT_ALARM + 220
#endif
} ItemActionType;

#endif
